services:
  frontend:
    image: sneaker-frontend
    container_name: sneaker-frontend
    build: 
      context: ./frontend
    environment:
      - VITE_BACKEND_SOCKET=${VITE_BACKEND_SOCKET}
      - VITE_PAYMENT_SOCKET=${VITE_PAYMENT_SOCKET}
      - NGINX_SERVER=${NGINX_SERVER}
    ports:
      - "3000:80"
    networks:
      - sneaker-shop-net
    depends_on:
      - backend

  backend:
    build: ./backend
    image: sneaker-backend
    container_name: sneaker-backend
    environment:
      - FRONTEND_SOCKET=${FRONTEND_SOCKET}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "8080:8080"
    networks:
      - sneaker-shop-net
    depends_on:
      database:
        condition: service_healthy

  logs:
    build: ./logs
    image: sneaker-logs
    container_name: sneaker-logs
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "8082:8082"
    networks:
      - sneaker-shop-net
    depends_on:
      database:
        condition: service_healthy

  analytics:
    build: ./analytics
    image: sneaker-analytics
    container_name: sneaker-analytics
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "8083:8083"
    networks:
      - sneaker-shop-net
    depends_on:
      database:
        condition: service_healthy

  payment:
    build: ./payment-service
    image: sneaker-payment
    container_name: sneaker-payment
    environment:
      - FRONTEND_SOCKET=${FRONTEND_SOCKET}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "8081:8081"
    networks:
      - sneaker-shop-net
    depends_on:
      database:
        condition: service_healthy
  
  database:
    build: ./database
    image: sneaker-database
    container_name: sneakerdb
    restart: always
    networks:
      - sneaker-shop-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      timeout: 3s
      retries: 3
      start_period: 5s
  
networks:
  sneaker-shop-net:
    name: sneaker-shop-net
    driver: bridge
